### ISSUE TITLE
Why doesn't it include all postal codes of indonesia?

### ISSUE THREAD

**Issue by mmanishh** [pentagonal/Indonesia-Postal-Code#1]
Hi,

Why doesn't it include all postal codes of indonesia? Since there are postal codes in indonesia too ?

**Comment by benyaminl** [comment]
> Hi,
> 
> Why doesn't it include all postal codes of indonesia? Since there are postal codes in indonesia too ?

it should, what area you can't find?

**Comment by pentagonal** [comment]
> Hi,
> 
> Why doesn't it include all postal codes of indonesia? Since there are postal codes in indonesia too ?

Btw this repo must / Should  include all Postal Codes.
Data has been validated..
But I do not know about nowaday ..
Maybe I will release new version from official civilian ministry..

**Comment by pentagonal** [comment]
Please use @arrayaccess repository on:

 https://github.com/ArrayAccess/Indonesia-Postal-And-Area
